print("What is git? Git is a free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency.")
print("Install git and create a GitHub account")
print("Add a new file to the repo")
print("Check the version of Git. 'git --version' Set up global config variables - If we are working with other developers, we need to know who is checking the code in and out, and to make the changes 'git config --global user.name “alvardall”  'git config --global user.email “alvardtel@gmail.com”")
print("Create a “Python_Course” repository ")
print("Check the status of the repository. git status")
print("Commit those changes to the repository's history with a short message. git commit -m ”added 1.py file”")
print("What is github. GitHub is an increasingly popular programming resource used for code sharing")
print("How to set up github repo")
print("git commands")