print("Extensions. Install Python Extension. First, click the Extensions tab.Second, type the pythonkeyword on the search input.Third, click the Python extension. It'll show detailed information on the right pane. Finally, click the Install button to install the Python extension")
print("To turn on or turn off the Auto Save feature in Visual Studio Code, we  go to File and click on Auto Save from the drop-down menu")
print("We did an exercise.Given two sides of a triangle, we had to calculate the diagonal")
print("Python Interpreter")
print("Interpreter vs compilers")
print("Zen of python")